apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argocd-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Fomainspi/argocd-project
    targetRevision: HEAD
    path: dev

  destination:
    server: https://kubernetes.default.svc
    namespace: webapp

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
