apiVersion: v1
kind: Service
metadata:
  name: maven-service
  namespace: webapp
spec:
  type: ClusterIP
  selector:
    app: maven-app
  ports:
    - protocol: TCP
      port: 80          # external LB port
      targetPort: 8080  # container's listening port
